name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone code to the runner
      uses: actions/checkout@v3
    - name: Build
      run: echo "Building the code..."
  lint: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Clone code to the runner
      uses: actions/checkout@v3
    - name: Lint
      run: echo "Linting the code..."
  test: 
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Clone code to the runner
      uses: actions/checkout@v3
    - name: Test
      run: echo "Testing the code..."
  Notify:
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    steps:
    - name: Send email
      run: echo "Notify relevant users..."
