name: Build, lint, and test
on: [push, pull_request]
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone code to the runner
      uses: actions/checkout@v3
    - name: Build
      run: echo "Building the code..."
    - name: Lint
      run: echo "Linting the code..."
    - name: Test
      run: echo "Testing the code..."
  notify:
    runs-on: ubuntu-latest
    needs: build-lint-test
    steps:
      - name: Notify recipient
        env:
         EMAIL: topg@gmail.com
        run: echo "Status notification sent to ${{ env.EMAIL }}..."
