name: Deployement
on: 
    push:
        branches:
        - main
jobs:
    build: 
        uses: dler-hasan/example-git-actions/blob/main/.github/workflows/build-lint-test.yaml@main
    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v3
    #     - name: Run a one-line script
    #       run: 
    # systest: 
    # prod: